#PBS    -N test
#PBS    -o jobs/test.out 
#PBS    -e jobs/test.err
#PBS    -l nodes=1:gpus=1:S
#PBS    -r y
cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE
startdocker -P /gdata/huangzp/hr_regan -D /gdata/huangzp/hr_regan -u "--ipc=host" -c "python /gdata/huangzp/hr_regan/main.py --num_gpu=1 --save_step=2 --log_step=2 --experiment_name='test'"  bit:5000/deepo
